services:
    routing_app.user_navigation_listener:
        class: "BugBuster\\RoutingappBundle\\EventListener\\UserNavigationListener"
        arguments:
            - "@request_stack"
            - "@router"
